name: "Heine"
description: "Hauptmarke Heine - Premium Getränke"
knowledge_base_path: "./data/knowledge/heine"
api_endpoint: "https://api.heine.com"
escalation_threshold: 0.7
support_email: "support@heine.com"
brand_voice: "professionell, freundlich, zuverlässig"
primary_language: "de"
supported_languages: ["de", "en"]

# Markenspezifische Einstellungen
brand_colors:
  primary: "#1a4b84"
  secondary: "#e6b800"

# Eskalationsregeln
escalation_rules:
  - trigger: "beschwerde"
    priority: "high"
    department: "kundenservice"
  - trigger: "bestellung"
    priority: "medium"
    department: "vertrieb"
  - trigger: "technisch"
    priority: "medium"
    department: "technik"

# Wissensdatenbank-Kategorien
knowledge_categories:
  - "produkte"
  - "bestellung"
  - "versand"
  - "rückgabe"
  - "allgemein"

# API-Endpunkte
api_endpoints:
  customer: "/customers/{customer_id}"
  order: "/orders/{order_id}"
  shipping: "/shipping/{tracking_id}"
  products: "/products" 