version: '3.8'

services:
  heine-ai:
    build: .
    container_name: heine-ai-system
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gpt-3.5-turbo}
      - MODEL_TEMPERATURE=${MODEL_TEMPERATURE:-0.7}
      - MODEL_MAX_TOKENS=${MODEL_MAX_TOKENS:-1000}
      - ESCALATION_THRESHOLD=${ESCALATION_THRESHOLD:-0.5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - VECTOR_STORE_PATH=/app/data/vector_store
      - LOGS_PATH=/app/data/logs
      - ESCALATION_TICKETS_PATH=/app/data/escalation_tickets
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis f端r Session-Management (f端r Produktion)
  redis:
    image: redis:7-alpine
    container_name: heine-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - production

  # Optional: PostgreSQL f端r persistente Daten (f端r Produktion)
  postgres:
    image: postgres:15-alpine
    container_name: heine-postgres
    environment:
      - POSTGRES_DB=heine_ai
      - POSTGRES_USER=heine_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-heine_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:
  postgres_data: 